
import { GoogleGenAI, Type, Modality } from "@google/genai";

if (!process.env.GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export const generateCaptions = async (imageBase64: string, mimeType: string): Promise<string[]> => {
  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: {
      parts: [
        {
          inlineData: {
            data: imageBase64,
            mimeType: mimeType,
          },
        },
        {
          text: "You are a witty meme expert. Analyze this image and generate 5 short, funny, one-liner captions suitable for a meme. The captions should be distinct from each other."
        }
      ],
    },
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          captions: {
            type: Type.ARRAY,
            items: {
              type: Type.STRING,
            },
            description: "An array of 5 funny meme captions.",
          },
        },
        required: ["captions"],
      },
    },
  });

  const jsonString = response.text.trim();
  const result = JSON.parse(jsonString);
  return result.captions;
};


export const editImage = async (imageBase64: string, mimeType: string, prompt: string): Promise<{newImageBase64: string, newMimeType: string}> => {
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: imageBase64,
            mimeType: mimeType,
          },
        },
        {
          text: prompt,
        },
      ],
    },
    config: {
        responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return {
        newImageBase64: part.inlineData.data,
        newMimeType: part.inlineData.mimeType,
      };
    }
  }

  throw new Error("No image was generated by the API.");
};

export const analyzeImage = async (imageBase64: string, mimeType: string): Promise<string> => {
  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: {
      parts: [
        {
          inlineData: {
            data: imageBase64,
            mimeType: mimeType,
          },
        },
        {
          text: "Analyze this image in detail. Describe the objects, people, setting, and potential context or mood. Be descriptive and insightful.",
        },
      ],
    },
  });

  return response.text;
};
